{
    "name": "Extensión personalizada de proyectos",
    "summary": "Fechas planeadas, garantías y migración del flujo de subtareas",
    "version": "18.0.1.1.0",
    "category": "Services/Project",
    "author": "TDP",
    "license": "LGPL-3",
    "depends": ["project"],
    "data": [
        "security/project_security.xml",
        "security/ir.model.access.csv",
        "views/res_config_settings_views.xml",
        "views/project_dashboard_views.xml",
        "views/project_detail_dashboard_views.xml",
        "views/project_project_views.xml",
        "views/project_task_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "project_custom_extension/static/src/dashboard/project_dashboard.js",
            "project_custom_extension/static/src/dashboard/project_dashboard.xml",
            "project_custom_extension/static/src/dashboard/project_dashboard.scss",
            "project_custom_extension/static/src/dashboard/project_detail_dashboard.js",
            "project_custom_extension/static/src/dashboard/project_detail_dashboard.xml",
            "project_custom_extension/static/src/dashboard/project_detail_dashboard.scss",
        ],
        "web.assets_unit_tests": [
            "project_custom_extension/static/tests/project_dashboard.test.js",
            "project_custom_extension/static/tests/project_detail_dashboard.test.js",
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
